# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-05 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisionSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=128)),
                ('session_name', models.CharField(max_length=128)),
                ('session_description', models.CharField(max_length=512)),
            ],
        ),
    ]
