# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-07 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvbapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visionsession',
            name='phase',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
