# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-10 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvbapp', '0002_visionsession_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=128)),
                ('vision_statement', models.CharField(max_length=512)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvbapp.VisionSession')),
            ],
        ),
    ]
