# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-13 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvbapp', '0004_visionstatement_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='visionsession',
            name='rc_channel',
            field=models.CharField(default='http://127.0.0.1:3000', max_length=256),
            preserve_default=False,
        ),
    ]
