# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-14 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvbapp', '0005_visionsession_rc_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=64)),
                ('channel_name', models.CharField(max_length=128)),
                ('rc_channel', models.CharField(max_length=256)),
            ],
        ),
    ]
