# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-14 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvbapp', '0006_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='visionsession',
            name='channel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cvbapp.Channel'),
            preserve_default=False,
        ),
    ]
