# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-14 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvbapp', '0007_visionsession_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visionsession',
            name='rc_channel',
        ),
    ]
