# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-18 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvbapp', '0009_scheduledmeetings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScheduledMeetings',
            new_name='ScheduledMeeting',
        ),
    ]
