# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvbapp', '0011_scheduledmeeting_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision_report', models.CharField(max_length=1024)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvbapp.VisionSession')),
            ],
        ),
    ]
