# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-05 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvbapp', '0014_auto_20180305_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='visionsession',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
